[project]
name = "greedy-lore"
version = "0.1.0"
description = "GreedyLore experiments"
readme = "readme.md"
requires-python = ">=3.11,<3.12"
dependencies = [
  "accelerate",
  "cupy-cuda12x",
  "datasets>=3.0.0",
  "evaluate",
  "loguru",
  "scikit-learn",
  "scipy",
  "torch==2.4.0",
  "torchaudio==2.4.0",
  "torchvision==0.19.0",
  "transformers",
  "wandb",
]

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }
torchaudio = { index = "pytorch-cu121" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
